/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GuardianCreateRouteImport } from './routes/guardian/create'
import { Route as GuardianDashboardRouteImport } from './routes/guardian/dashboard'
import { Route as GuardianMonitorRouteImport } from './routes/guardian/monitor'
import { Route as GuardianReportsRouteImport } from './routes/guardian/reports'
import { Route as GuardianSettingsRouteImport } from './routes/guardian/settings'
import { Route as GuardianWaiting_for_connectionRouteImport } from './routes/guardian/waiting_for_connection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianCreateRoute = GuardianCreateRouteImport.update({
  id: '/guardian/create',
  path: '/guardian/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/guardian/dashboard',
  path: '/guardian/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianMonitorRoute = GuardianMonitorRouteImport.update({
  id: '/guardian/monitor',
  path: '/guardian/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianReportsRoute = GuardianReportsRouteImport.update({
  id: '/guardian/reports',
  path: '/guardian/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianSettingsRoute = GuardianSettingsRouteImport.update({
  id: '/guardian/settings',
  path: '/guardian/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianWaiting_for_connectionRoute =
  GuardianWaiting_for_connectionRouteImport.update({
    id: '/guardian/waiting_for_connection',
    path: '/guardian/waiting_for_connection',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/shop': typeof ShopRoute
  '/guardian/create': typeof GuardianCreateRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/monitor': typeof GuardianMonitorRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/guardian/waiting_for_connection': typeof GuardianWaiting_for_connectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/shop': typeof ShopRoute
  '/guardian/create': typeof GuardianCreateRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/monitor': typeof GuardianMonitorRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/guardian/waiting_for_connection': typeof GuardianWaiting_for_connectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/shop': typeof ShopRoute
  '/guardian/create': typeof GuardianCreateRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/monitor': typeof GuardianMonitorRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/settings': typeof GuardianSettingsRoute
  '/guardian/waiting_for_connection': typeof GuardianWaiting_for_connectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/shop'
    | '/guardian/create'
    | '/guardian/dashboard'
    | '/guardian/monitor'
    | '/guardian/reports'
    | '/guardian/settings'
    | '/guardian/waiting_for_connection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/shop'
    | '/guardian/create'
    | '/guardian/dashboard'
    | '/guardian/monitor'
    | '/guardian/reports'
    | '/guardian/settings'
    | '/guardian/waiting_for_connection'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/shop'
    | '/guardian/create'
    | '/guardian/dashboard'
    | '/guardian/monitor'
    | '/guardian/reports'
    | '/guardian/settings'
    | '/guardian/waiting_for_connection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ShopRoute: typeof ShopRoute
  GuardianCreateRoute: typeof GuardianCreateRoute
  GuardianDashboardRoute: typeof GuardianDashboardRoute
  GuardianMonitorRoute: typeof GuardianMonitorRoute
  GuardianReportsRoute: typeof GuardianReportsRoute
  GuardianSettingsRoute: typeof GuardianSettingsRoute
  GuardianWaiting_for_connectionRoute: typeof GuardianWaiting_for_connectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/create': {
      id: '/guardian/create'
      path: '/guardian/create'
      fullPath: '/guardian/create'
      preLoaderRoute: typeof GuardianCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/guardian/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/monitor': {
      id: '/guardian/monitor'
      path: '/guardian/monitor'
      fullPath: '/guardian/monitor'
      preLoaderRoute: typeof GuardianMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/reports': {
      id: '/guardian/reports'
      path: '/guardian/reports'
      fullPath: '/guardian/reports'
      preLoaderRoute: typeof GuardianReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/settings': {
      id: '/guardian/settings'
      path: '/guardian/settings'
      fullPath: '/guardian/settings'
      preLoaderRoute: typeof GuardianSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/waiting_for_connection': {
      id: '/guardian/waiting_for_connection'
      path: '/guardian/waiting_for_connection'
      fullPath: '/guardian/waiting_for_connection'
      preLoaderRoute: typeof GuardianWaiting_for_connectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ShopRoute: ShopRoute,
  GuardianCreateRoute: GuardianCreateRoute,
  GuardianDashboardRoute: GuardianDashboardRoute,
  GuardianMonitorRoute: GuardianMonitorRoute,
  GuardianReportsRoute: GuardianReportsRoute,
  GuardianSettingsRoute: GuardianSettingsRoute,
  GuardianWaiting_for_connectionRoute: GuardianWaiting_for_connectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
